map_name: full_divider_salad_4
recipes: ["LettuceSalad",
          "TomatoSalad",
          "ChoppedCarrot",
          "ChoppedOnion",
          "TomatoLettuceSalad",
          "TomatoCarrotSalad"]

horizon: 200
obs_spaces_type: dense

num_agents: 2
interact_reward: 0.5
progress_reward: 1.0
complete_reward: 10.0
step_cost: 0.05
return_z: False

env_wrappers: [ZWrapper, AgentIDWrapper, StateWrapper]
wrapper_args:
  z_dim: 8
  z_discrete: True
  shared_z: False
